### ISSUE TITLE
Create the final report document in overleaf, fill with appropriate sections

### ISSUE THREAD

**Issue by HolgerStenberg** [IL2232-HT2022-HIL/IL2232-HT2022-HIL#16]
Style and size of a Master thesis (~60-70 pages). 
Grammar and spell-checked.

Create the report file on overleaf.com and invite all members, including Matthias Becker to the document. It is beneficial to start early with the report in order to experience less time constraints later. Once the document is created, find the template used for master thesises at KTH and then inform all members of the document

**Comment by HolgerStenberg** [comment]
@matthiasthomasbecker Do you know if there is a standard template for Master Thesis report available?

**Comment by HolgerStenberg** [comment]
https://www.overleaf.com/2587237728xcvsncrptrcs

@Fkar97, @olleblo , @sofiecmf, @Yuxiaowa , @WCL-26 
Now you can join the project. Still looking for some kind of template

**Comment by matthiasthomasbecker** [comment]
This one is provided for some master thesis courses https://www.overleaf.com/project/618a5f2bbcb59a8a1cb07e34

**Comment by HolgerStenberg** [comment]
I think I found the same file. Should be a good start!

**Comment by HolgerStenberg** [comment]
Jhonny has decided to upload a template in canvas, we are awaiting that template

**Comment by HolgerStenberg** [comment]
this is now cleared up
