### ISSUE TITLE
Risk analysis document

### ISSUE THREAD

**Issue by olleblo** [IL2232-HT2022-HIL/IL2232-HT2022-HIL#4]

**Comment by HolgerStenberg** [comment]
https://www.overleaf.com/4669254231pkrhzstjzrrp

**Comment by sofiecmf** [comment]
**Draft of risk analysis**

@team, I added responsibility and deadlines to the actions as the instructions wanted that to be stated, so take those additions with a grain of salt. We can discuss them in the meeting tomorrow.

@matthiasthomasbecker, Please have a look if you have the time and let us know what you think of our risk analysis draft :)

[IL2232_Risk_Analysis_Protocol-3.pdf](https://github.com/IL2232-HT2022-HIL/IL2232-HT2022-HIL/files/9659281/IL2232_Risk_Analysis_Protocol-3.pdf)

**Comment by matthiasthomasbecker** [comment]
Hi all,
I had a look at the risk analysis and it looks good to me. All major risks are covered. 
Best regards,
Matthias
